// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR6Wq8TMIQqz0IUrlmaYnPx1JS_sLUmFw',
    appId: '1:274615845708:web:d6731afd290ab7431c05e9',
    messagingSenderId: '274615845708',
    projectId: 'money-69859',
    authDomain: 'money-69859.firebaseapp.com',
    storageBucket: 'money-69859.firebasestorage.app',
    measurementId: 'G-S157XR87XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVPrQQG4bVOw3kmQbhZ--fCG-RQFQeXCg',
    appId: '1:274615845708:android:424de06e2d82ac7d1c05e9',
    messagingSenderId: '274615845708',
    projectId: 'money-69859',
    storageBucket: 'money-69859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBUy9MuTUwKONZaZps8joSOwVqNsRyuI4',
    appId: '1:274615845708:ios:8d404c2e541d240e1c05e9',
    messagingSenderId: '274615845708',
    projectId: 'money-69859',
    storageBucket: 'money-69859.firebasestorage.app',
    androidClientId: '274615845708-g14mj6u875uikjofj9f3esp05i541okl.apps.googleusercontent.com',
    iosClientId: '274615845708-6qa5h8mh0mjl14rgr5g13vcpn53vqdte.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletExe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBUy9MuTUwKONZaZps8joSOwVqNsRyuI4',
    appId: '1:274615845708:ios:8d404c2e541d240e1c05e9',
    messagingSenderId: '274615845708',
    projectId: 'money-69859',
    storageBucket: 'money-69859.firebasestorage.app',
    androidClientId: '274615845708-g14mj6u875uikjofj9f3esp05i541okl.apps.googleusercontent.com',
    iosClientId: '274615845708-6qa5h8mh0mjl14rgr5g13vcpn53vqdte.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletExe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR6Wq8TMIQqz0IUrlmaYnPx1JS_sLUmFw',
    appId: '1:274615845708:web:d8084771fcdc4d421c05e9',
    messagingSenderId: '274615845708',
    projectId: 'money-69859',
    authDomain: 'money-69859.firebaseapp.com',
    storageBucket: 'money-69859.firebasestorage.app',
    measurementId: 'G-JNPYQ8K66Q',
  );

}